name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
      
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Release please
      uses: google-github-actions/release-please-action@v3.1.2
      with:
        path: server
        release-type: rust
